"""agregar_clerk_id_a_usuarios

Revision ID: 9c18ebd8ef5f
Revises: 20260710_0005
Create Date: 2026-07-19 21:18:32.191957
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9c18ebd8ef5f'
down_revision = '20260710_0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'apuestas', 'peleadores', ['peleador_seleccionado_id'], ['id'])
    op.create_foreign_key(None, 'apuestas', 'peleas', ['pelea_id'], ['id'])
    op.drop_constraint(op.f('billeteras_usuario_id_key'), 'billeteras', type_='unique')
    op.drop_constraint(op.f('peleadores_nombre_key'), 'peleadores', type_='unique')
    op.create_foreign_key(None, 'predicciones', 'peleas', ['pelea_id'], ['id'])
    op.drop_constraint(op.f('recargas_stripe_session_id_key'), 'recargas', type_='unique')
    op.create_foreign_key(None, 'resultados', 'peleadores', ['ganador_id'], ['id'])
    op.create_foreign_key(None, 'resultados', 'peleas', ['pelea_id'], ['id'])
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('uq_usuarios_clerk_id'), table_name='usuarios')
    op.drop_index(op.f('uq_usuarios_nombre'), table_name='usuarios')
    op.create_unique_constraint('uq_usuarios_nombre', 'usuarios', ['nombre'])
    op.create_index(op.f('ix_usuarios_clerk_id'), 'usuarios', ['clerk_id'], unique=True)
    op.create_index(op.f('ix_usuarios_nombre'), 'usuarios', ['nombre'], unique=True)
    op.create_unique_constraint(None, 'usuarios', ['cedula'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_index(op.f('ix_usuarios_nombre'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_clerk_id'), table_name='usuarios')
    op.drop_constraint('uq_usuarios_nombre', 'usuarios', type_='unique')
    op.create_index(op.f('uq_usuarios_nombre'), 'usuarios', ['nombre'], unique=True)
    op.create_index(op.f('uq_usuarios_clerk_id'), 'usuarios', ['clerk_id'], unique=True)
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'resultados', type_='foreignkey')
    op.drop_constraint(None, 'resultados', type_='foreignkey')
    op.create_unique_constraint(op.f('recargas_stripe_session_id_key'), 'recargas', ['stripe_session_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'predicciones', type_='foreignkey')
    op.create_unique_constraint(op.f('peleadores_nombre_key'), 'peleadores', ['nombre'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('billeteras_usuario_id_key'), 'billeteras', ['usuario_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'apuestas', type_='foreignkey')
    op.drop_constraint(None, 'apuestas', type_='foreignkey')
    # ### end Alembic commands ###
